name: Go Tests
on: [push, pull_request]
jobs:
  go_tests:
    strategy:
      k:
        go-version: [1.14.x, 1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ k.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ k.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Download Dependencies
        run: go get -v -t -d ./...

      - name: Test
        run: go test -v ./...