# .github/workflows/release.yaml
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
          - goarch: amd64
            goos: darwin
          - goarch: arm64
            goos: linux
          - goarch: arm64
            goos: darwin
    steps:
    - uses: actions/checkout@master
    - name: Set up Go
      uses: actions/setup-go@v2
      with: 
        go-version: 1.16
    - name: build
      run: go build .
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
    - name: Packaging...
      run: tar czf main-${{ matrix.goos }}-${{ matrix.goarch }}.tgz main
    - name: Uploading assets...
      if: ${{ !env.ACT }}
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TEST }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./main-${{ matrix.goos }}-${{ matrix.goarch }}.tgz
        asset_name: main-${{ matrix.goos }}-${{ matrix.goarch }}.tgz
        asset_content_type: application/gzip        
